#!/bin/bash

#仅在configure执行时使用，一般设置为模块名称
ngx_addon_name=ngx_http_mytest_module

#保存所有的HTTP模块的名称
HTTP_MODULES="$HTTP_MODULES ngx_http_mytest_module"

#用于指定新增模块的源代码
NGX_ADDON_SRCS="$NGX_ADDON_SRCS $ngx_addon_dir/ngx_http_mytest_module.c"
